[package]
name = "ca65-lsp-instruction-doc-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }

[profile.dev]
opt-level = 0
debug = "full"
